### PR TITLE
Improve tree-sitter support

### PR DESCRIPTION
**Pull request by stsewd**
This is a port from https://github.com/ayu-theme/ayu-vim/pull/61

I think parameters should be different from normal vars.

### CODE REVIEW

**Comment by Luxed** [comment]
I agree with this change, but I don't think blue would be a good color.
If we use TypeScript as an example (which I'm not using with TreeSitter right now because of installation issues on Windows, but still), it would mean that both the parameter and the type would be of the same color.
How about using the "special" color instead?

**Comment by ameertaweel** [comment]
Any news on this?

**Comment by Luxed** [comment]
> Any news on this?

I'm not a fan of the changes.
Parameters are currently highlighted as "special" which makes more sense than "entity" to me.
Then, the delimiters are already highlighted correctly, so I don't really understand the change.
Does the current highlighting bother you?

**Comment by Luxed** [comment]
Closed by 8b8b4c6.
For users without `g:ayu_extended_palette`, the parameter highlight is "special", with the extended palette enabled, it is instead a custom color that is only a shade of the "normal" color (that variables use).

**Pull request closed without merging**
